# 11-30-23 Austin Faulkenburg President Project 
presidents = [['weight', 5, ("George Washington", 175),("John Adams", 150),("Thomas Jefferson", 174),("James Madison\n Highly educated for the time\n president during the war\n of 1812\n his house burned down", 100),
              ("James Monroe\n The last of the \n Founding Fauther Presidents", 189),("John Quincy Adams", 175),("Andrew Jackson\n One of the most contraversial presidents\n lead the trail of tears\n that removed the indians from the east\n famouse general from the ar of 1812\n defeated the british at the battle of \n new orleans prior to taking office", 140),
              ("Martin Van Buren", 164),("William Henry Harrison", 162),("John Tyler", 160),("James K Polk", 174),
              ("Zachary Taylor", 170),("Millard Fillmore", 174),("Franklin Pierce", 144),("James Buchanan", 198),
              ("Abraham Lincoln\nWas very tall\n had a famed wrestling\n career before taking\n office, and was a lawyer", 180),("Andrew Johnson", 174),("Ulysses S Grant\n Civil War hero- general\n a reconstruction president", 156),("Rutherford B Hayes", 175),
              ("James A Garfield", 184),("Chester A Arthur", 224),("Grover Cleveland\n Cleveland was a gilded age \npresident supporting the \ngold standard\n and taking on labor strikes", 260),("Benjamin Harrison", 160),
              ("William Mckinley", 199),("Theodore Roosevelt", 210),("William H Taft\n The fattest president was off the chart! He is belived \nto have been stuck in his bathtub at the whitehouse.", 340),("Woodrow Wilson", 170),
              ("Warren G Harding", 173),("Calvin Coolidge\n Supported womens sufferage, \n but did not support prohibition", 148),("Herbert Hoover", 187),("Franklin D Roosevelt", 188),
              ("Harry S Truman", 167),("Dwight D Eisenhower", 171),("John F Kennedy", 173),("Lyndon B Johnson", 200),
              ("Richard M Nixon", 173),("Gerald R Ford", 190),("Jimmy Carter\n Was president during the 3 mile island nuclear incident\n personally visited the reacter as a nuclear engineer from the navy", 160),("Ronald Reagan", 185),("George H W Bush", 196),
              ("Bill Clinton", 223),("George W Bush", 191),("Barack Obama", 180),("Donald J Trump \n Was one of the\n heaviest presidents \nin the 20th century \n due to his time as\n a wealthy buisiness \nman  prior to taking \noffice.", 239),("Joe Biden", 178)]]
  